package com.olym.mjt.config;

import android.content.res.Resources;
import com.olym.mjt.module.MjtApplication;
import java.util.HashMap;

public class SipReasonCode
{
    public static final int SWITCH_CAUSE_ACCESS_INFO_DISCARDED = 43;
    public static final int SWITCH_CAUSE_ALLOTTED_TIMEOUT = 602;
    public static final int SWITCH_CAUSE_ATTENDED_TRANSFER = 601;
    public static final int SWITCH_CAUSE_BEARERCAPABILITY_NOTAUTH = 57;
    public static final int SWITCH_CAUSE_BEARERCAPABILITY_NOTAVAIL = 58;
    public static final int SWITCH_CAUSE_BEARERCAPABILITY_NOTIMPL = 65;
    public static final int SWITCH_CAUSE_BLIND_TRANSFER = 600;
    public static final int SWITCH_CAUSE_CALL_AWARDED_DELIVERED = 7;
    public static final int SWITCH_CAUSE_CALL_REJECTED = 21;
    public static final int SWITCH_CAUSE_CHANNEL_UNACCEPTABLE = 6;
    public static final int SWITCH_CAUSE_CHAN_NOT_IMPLEMENTED = 66;
    public static final int SWITCH_CAUSE_CRASH = 500;
    public static final int SWITCH_CAUSE_DESTINATION_OUT_OF_ORDER = 27;
    public static final int SWITCH_CAUSE_EXCHANGE_ROUTING_ERROR = 25;
    public static final int SWITCH_CAUSE_FACILITY_NOT_IMPLEMENTED = 69;
    public static final int SWITCH_CAUSE_FACILITY_NOT_SUBSCRIBED = 50;
    public static final int SWITCH_CAUSE_FACILITY_REJECTED = 29;
    public static final int SWITCH_CAUSE_GATEWAY_DOWN = 609;
    public static final int SWITCH_CAUSE_IE_NONEXIST = 99;
    public static final int SWITCH_CAUSE_INCOMING_CALL_BARRED = 54;
    public static final int SWITCH_CAUSE_INCOMPATIBLE_DESTINATION = 88;
    public static final int SWITCH_CAUSE_INTERWORKING = 127;
    public static final int SWITCH_CAUSE_INVALID_CALL_REFERENCE = 81;
    public static final int SWITCH_CAUSE_INVALID_GATEWAY = 608;
    public static final int SWITCH_CAUSE_INVALID_IE_CONTENTS = 100;
    public static final int SWITCH_CAUSE_INVALID_MSG_UNSPECIFIED = 95;
    public static final int SWITCH_CAUSE_INVALID_NUMBER_FORMAT = 28;
    public static final int SWITCH_CAUSE_INVALID_PROFILE = 611;
    public static final int SWITCH_CAUSE_INVALID_URL = 610;
    public static final int SWITCH_CAUSE_LOSE_RACE = 502;
    public static final int SWITCH_CAUSE_MANAGER_REQUEST = 503;
    public static final int SWITCH_CAUSE_MANDATORY_IE_LENGTH_ERROR = 103;
    public static final int SWITCH_CAUSE_MANDATORY_IE_MISSING = 96;
    public static final int SWITCH_CAUSE_MEDIA_TIMEOUT = 604;
    public static final int SWITCH_CAUSE_MESSAGE_TYPE_NONEXIST = 97;
    public static final int SWITCH_CAUSE_NETWORK_OUT_OF_ORDER = 38;
    public static final int SWITCH_CAUSE_NONE = 0;
    public static final int SWITCH_CAUSE_NORMAL_CIRCUIT_CONGESTION = 34;
    public static final int SWITCH_CAUSE_NORMAL_CLEARING = 16;
    public static final int SWITCH_CAUSE_NORMAL_HANGUP = 200;
    public static final int SWITCH_CAUSE_NORMAL_TEMPORARY_FAILURE = 41;
    public static final int SWITCH_CAUSE_NORMAL_UNSPECIFIED = 31;
    public static final int SWITCH_CAUSE_NO_ANSWER = 19;
    public static final int SWITCH_CAUSE_NO_PICKUP = 612;
    public static final int SWITCH_CAUSE_NO_ROUTE_DESTINATION = 3;
    public static final int SWITCH_CAUSE_NO_ROUTE_TRANSIT_NET = 2;
    public static final int SWITCH_CAUSE_NO_USER_RESPONSE = 18;
    public static final int SWITCH_CAUSE_NUMBER_CHANGED = 22;
    public static final int SWITCH_CAUSE_ORIGINATOR_CANCEL = 487;
    public static final int SWITCH_CAUSE_OUTGOING_CALL_BARRED = 52;
    public static final int SWITCH_CAUSE_PICKED_OFF = 605;
    public static final int SWITCH_CAUSE_PRE_EMPTED = 45;
    public static final int SWITCH_CAUSE_PROGRESS_TIMEOUT = 607;
    public static final int SWITCH_CAUSE_PROTOCOL_ERROR = 111;
    public static final int SWITCH_CAUSE_RECOVERY_ON_TIMER_EXPIRE = 102;
    public static final int SWITCH_CAUSE_REDIRECTION_TO_NEW_DESTINATION = 23;
    public static final int SWITCH_CAUSE_REQUESTED_CHAN_UNAVAIL = 44;
    public static final int SWITCH_CAUSE_RESPONSE_TO_STATUS_ENQUIRY = 30;
    public static final int SWITCH_CAUSE_SERVICE_NOT_IMPLEMENTED = 79;
    public static final int SWITCH_CAUSE_SERVICE_UNAVAILABLE = 63;
    public static final int SWITCH_CAUSE_SRTP_READ_ERROR = 613;
    public static final int SWITCH_CAUSE_SUBSCRIBER_ABSENT = 20;
    public static final int SWITCH_CAUSE_SUCCESS = 142;
    public static final int SWITCH_CAUSE_SWITCH_CONGESTION = 42;
    public static final int SWITCH_CAUSE_SYSTEM_SHUTDOWN = 501;
    public static final int SWITCH_CAUSE_UNALLOCATED_NUMBER = 1;
    public static final int SWITCH_CAUSE_USER_BUSY = 17;
    public static final int SWITCH_CAUSE_USER_CHALLENGE = 603;
    public static final int SWITCH_CAUSE_USER_NOT_REGISTERED = 606;
    public static final int SWITCH_CAUSE_WRONG_CALL_STATE = 101;
    public static final int SWITCH_CAUSE_WRONG_MESSAGE = 98;
    public static HashMap<Integer, String> sipTips = new HashMap();

    static
    {
        sipTips.put(Integer.valueOf(0), MjtApplication.getInstance().getResources().getString(2131689511));
        sipTips.put(Integer.valueOf(1), MjtApplication.getInstance().getResources().getString(2131689540));
        sipTips.put(Integer.valueOf(2), MjtApplication.getInstance().getResources().getString(2131689520));
        sipTips.put(Integer.valueOf(3), MjtApplication.getInstance().getResources().getString(2131689519));
        sipTips.put(Integer.valueOf(6), MjtApplication.getInstance().getResources().getString(2131689484));
        sipTips.put(Integer.valueOf(7), MjtApplication.getInstance().getResources().getString(2131689482));
        sipTips.put(Integer.valueOf(16), MjtApplication.getInstance().getResources().getString(2131689513));
        sipTips.put(Integer.valueOf(17), MjtApplication.getInstance().getResources().getString(2131689541));
        sipTips.put(Integer.valueOf(18), MjtApplication.getInstance().getResources().getString(2131689521));
        sipTips.put(Integer.valueOf(19), MjtApplication.getInstance().getResources().getString(2131689517));
        sipTips.put(Integer.valueOf(20), MjtApplication.getInstance().getResources().getString(2131689536));
        sipTips.put(Integer.valueOf(21), MjtApplication.getInstance().getResources().getString(2131689483));
        sipTips.put(Integer.valueOf(22), MjtApplication.getInstance().getResources().getString(2131689522));
        sipTips.put(Integer.valueOf(23), MjtApplication.getInstance().getResources().getString(2131689530));
        sipTips.put(Integer.valueOf(25), MjtApplication.getInstance().getResources().getString(2131689488));
        sipTips.put(Integer.valueOf(27), MjtApplication.getInstance().getResources().getString(2131689487));
        sipTips.put(Integer.valueOf(28), MjtApplication.getInstance().getResources().getString(2131689501));
        sipTips.put(Integer.valueOf(29), MjtApplication.getInstance().getResources().getString(2131689491));
        sipTips.put(Integer.valueOf(30), MjtApplication.getInstance().getResources().getString(2131689532));
        sipTips.put(Integer.valueOf(31), MjtApplication.getInstance().getResources().getString(2131689516));
        sipTips.put(Integer.valueOf(34), MjtApplication.getInstance().getResources().getString(2131689512));
        sipTips.put(Integer.valueOf(38), MjtApplication.getInstance().getResources().getString(2131689510));
        sipTips.put(Integer.valueOf(41), MjtApplication.getInstance().getResources().getString(2131689515));
        sipTips.put(Integer.valueOf(42), MjtApplication.getInstance().getResources().getString(2131689538));
        sipTips.put(Integer.valueOf(43), MjtApplication.getInstance().getResources().getString(2131689475));
        sipTips.put(Integer.valueOf(44), MjtApplication.getInstance().getResources().getString(2131689531));
        sipTips.put(Integer.valueOf(45), MjtApplication.getInstance().getResources().getString(2131689526));
        sipTips.put(Integer.valueOf(50), MjtApplication.getInstance().getResources().getString(2131689490));
        sipTips.put(Integer.valueOf(52), MjtApplication.getInstance().getResources().getString(2131689524));
        sipTips.put(Integer.valueOf(54), MjtApplication.getInstance().getResources().getString(2131689494));
        sipTips.put(Integer.valueOf(57), MjtApplication.getInstance().getResources().getString(2131689478));
        sipTips.put(Integer.valueOf(58), MjtApplication.getInstance().getResources().getString(2131689479));
        sipTips.put(Integer.valueOf(63), MjtApplication.getInstance().getResources().getString(2131689534));
        sipTips.put(Integer.valueOf(65), MjtApplication.getInstance().getResources().getString(2131689480));
        sipTips.put(Integer.valueOf(66), MjtApplication.getInstance().getResources().getString(2131689485));
        sipTips.put(Integer.valueOf(69), MjtApplication.getInstance().getResources().getString(2131689489));
        sipTips.put(Integer.valueOf(79), MjtApplication.getInstance().getResources().getString(2131689533));
        sipTips.put(Integer.valueOf(81), MjtApplication.getInstance().getResources().getString(2131689497));
        sipTips.put(Integer.valueOf(88), MjtApplication.getInstance().getResources().getString(2131689495));
        sipTips.put(Integer.valueOf(95), MjtApplication.getInstance().getResources().getString(2131689500));
        sipTips.put(Integer.valueOf(96), MjtApplication.getInstance().getResources().getString(2131689507));
        sipTips.put(Integer.valueOf(97), MjtApplication.getInstance().getResources().getString(2131689509));
        sipTips.put(Integer.valueOf(98), MjtApplication.getInstance().getResources().getString(2131689545));
        sipTips.put(Integer.valueOf(99), MjtApplication.getInstance().getResources().getString(2131689493));
        sipTips.put(Integer.valueOf(100), MjtApplication.getInstance().getResources().getString(2131689499));
        sipTips.put(Integer.valueOf(101), MjtApplication.getInstance().getResources().getString(2131689544));
        sipTips.put(Integer.valueOf(102), MjtApplication.getInstance().getResources().getString(2131689529));
        sipTips.put(Integer.valueOf(103), MjtApplication.getInstance().getResources().getString(2131689506));
        sipTips.put(Integer.valueOf(111), MjtApplication.getInstance().getResources().getString(2131689528));
        sipTips.put(Integer.valueOf(127), MjtApplication.getInstance().getResources().getString(2131689496));
        sipTips.put(Integer.valueOf(142), MjtApplication.getInstance().getResources().getString(2131689537));
        sipTips.put(Integer.valueOf(200), MjtApplication.getInstance().getResources().getString(2131689514));
        sipTips.put(Integer.valueOf(487), MjtApplication.getInstance().getResources().getString(2131689523));
        sipTips.put(Integer.valueOf(500), MjtApplication.getInstance().getResources().getString(2131689486));
        sipTips.put(Integer.valueOf(501), MjtApplication.getInstance().getResources().getString(2131689539));
        sipTips.put(Integer.valueOf(502), MjtApplication.getInstance().getResources().getString(2131689504));
        sipTips.put(Integer.valueOf(503), MjtApplication.getInstance().getResources().getString(2131689505));
        sipTips.put(Integer.valueOf(600), MjtApplication.getInstance().getResources().getString(2131689481));
        sipTips.put(Integer.valueOf(601), MjtApplication.getInstance().getResources().getString(2131689477));
        sipTips.put(Integer.valueOf(602), MjtApplication.getInstance().getResources().getString(2131689476));
        sipTips.put(Integer.valueOf(603), MjtApplication.getInstance().getResources().getString(2131689542));
        sipTips.put(Integer.valueOf(604), MjtApplication.getInstance().getResources().getString(2131689508));
        sipTips.put(Integer.valueOf(605), MjtApplication.getInstance().getResources().getString(2131689525));
        sipTips.put(Integer.valueOf(606), MjtApplication.getInstance().getResources().getString(2131689543));
        sipTips.put(Integer.valueOf(607), MjtApplication.getInstance().getResources().getString(2131689527));
        sipTips.put(Integer.valueOf(608), MjtApplication.getInstance().getResources().getString(2131689498));
        sipTips.put(Integer.valueOf(609), MjtApplication.getInstance().getResources().getString(2131689492));
        sipTips.put(Integer.valueOf(610), MjtApplication.getInstance().getResources().getString(2131689503));
        sipTips.put(Integer.valueOf(611), MjtApplication.getInstance().getResources().getString(2131689502));
        sipTips.put(Integer.valueOf(612), MjtApplication.getInstance().getResources().getString(2131689518));
        sipTips.put(Integer.valueOf(613), MjtApplication.getInstance().getResources().getString(2131689535));
    }
}
